# Copyright (c) Bao Project and Contributors. All rights reserved
#
# SPDX-License-Identifier: Apache-2.0
---
bao_cfg:
  cross_compile: ~
  demo: baremetal
  toolchain_path: /home/diogo/
bao_test_cfg:
  log_level: 2
  setups:
    - tests1.yaml
platform_cfg:
  platform:
    - qemu-aarch64-virt
