name: Bao component base workflow

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:

  gitlint:
    runs-on: ubuntu-latest
    container: baoproject/bao:latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0
      - run: git config --global --add safe.directory $(realpath .)
      - if: ${{ github.event_name == 'pull_request' }}
        run: make gitlint GITLINT_BASE=${{ github.event.pull_request.base.sha }}
      - if: ${{ github.event_name == 'push' }}
        run: make gitlint GITLINT_BASE=${{ github.event.before }}
      - if: ${{ github.event_name == 'workflow_dispatch' }}
        run: make gitlint GITLINT_BASE=HEAD
  
  license:
    runs-on: ubuntu-latest
    container: baoproject/bao:latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0
      - run: >
          make license-check

  coding-style:
    runs-on: ubuntu-latest
    container: baoproject/bao:latest
    strategy:
      matrix:
        platform: ["qemu-aarch64-virt"]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - run: make PLATFORM=${{ matrix.platform }} format-check

  static-analysis:
    runs-on: ubuntu-latest
    container: baoproject/bao:latest
    strategy:
      matrix:
        platform: ["qemu-aarch64-virt"]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - run: make PLATFORM=${{ matrix.platform }} tidy
      - run: make PLATFORM=${{ matrix.platform }} cppcheck

  pylint:
    runs-on: ubuntu-latest
    container: baoproject/bao:latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0
      - run: >
          make pylint

  yamllint:
    runs-on: ubuntu-latest
    container: baoproject/bao:latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0
      - run: >
          make yamllint